### ISSUE TITLE
[BUG] - Telemtry.py

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#128]
**Describe the bug**
When asking Alice what temperature is it inside she doesn't recognise the stored data from the database.

Reason for this is that on line 48 of telemetry.py

 ```data = self.TelemetryManager.getData(siteId=siteId, ttype=TelemetryType(telemetryType))```

 returns
 ```<sqlite3.Row object at 0x68b8d9c0>```

 rather than the values. 

changing data to tuple fixed this for me

In addition ... line 51  is looking for 'value' but there is no 'value' in the var data
therefore line 53 ? is 

```answer = f"{data['value']} {self._telemetryUnits.get(telemetryType, '')}" ```
 returns nothing. i changed the whole section to the below and i get the expected results. however i'm sure theres a better way to do it :)

```
    data = self.TelemetryManager.getData(siteId=siteId, ttype=TelemetryType(telemetryType))
		data = tuple(data)
		if data:
			answer = f"{data[0]} {self._telemetryUnits.get(telemetryType, '')}"
			self.endDialog(sessionId=session.sessionId, text=self.randomTalk('answerInstant').format(answer))
		else:
			self.endDialog(sessionId=session.sessionId, text=self.randomTalk('noData'))
```

**Comment by philipp2310** [comment]
fixed in that way in your commit: [f4f93955b3c63dc2062a74d103e151eddbbfcee3](https://github.com/project-alice-assistant/skill_Telemetry/commit/f4f93955b3c63dc2062a74d103e151eddbbfcee3)

yet working with the sqlite3.Row object should work.
re-added check if "data" exists at all -> Nonetype not iterable if no data exists in the database
removed the "data" declaration as tuple -> Row has the array access itself

Finally I figured out what the problem before was: 'value' in data is not working, but 'value' in data.keys() is working and is the way to go with sqlite3.Row

Thanks for reporting and providing the quick fix!
