### ISSUE TITLE
Skills from other sources

### ISSUE THREAD

**Issue by DanBmh** [project-alice-powered-by-snips/ProjectAliceModules#97]
Do you plan to support the usage of skills from other repositories, git hosters like gitlab.com or self hosted repositories as snips did?
This would also allow the use of different licenses. I used AGPL instead of GPL for all of my snips skills.

**Comment by Psychokiller1888** [comment]
Not for released skills, no. Every single skill that is released here is read through by at least Max and me, to make sure it is safe to deploy

**Comment by DanBmh** [comment]
Ok, thanks for the fast answer.

**Comment by maxbachmann** [comment]
@DanBmh Mycroft handles this different, so they have a skill repo with submodules.
An apparent advantage is as you say, that people can maintain it in different places. However this can be a big problem aswell, since it makes it harder for others to help especially in  case the skill creator is not very active this results in 'dead' skills, where people add e.g. translations, but they never get merged or even commented on.
